import { Champion } from "../components/Champion.interface";

export const allChampions: Champion[] = [
  {
    src: "/imgs/icons/champions/tft8_alistar_square.tft_set8.png",
    name: "Alistar",
    origin: ["Ox Force"],
    class: ["Aegis", "Mascot"],
    cost: 3,
  },
  {
    src: "/imgs/icons/champions/tft8_annie_square.tft_set8.png",
    name: "Annie",
    origin: ["Ox Force", "Gadgeteen"],
    class: ["Spellslinger"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_aphelios_square.tft_set8.png",
    name: "Aphelios",
    origin: ["Ox Force", "Arsenal"],
    class: ["Sureshot"],
    cost: 5,
  },
  {
    src: "/imgs/icons/champions/tft8_ashe_square.tft_set8.png",
    name: "Ashe",
    origin: ["Laser Corps"],
    class: ["Recon"],
    cost: 1,
  },
  {
    src: "/imgs/icons/champions/tft8_aurelionsol_square.tft_set8.png",
    name: "Aurelion Sol",
    origin: ["Threat"],
    class: [""],
    cost: 4,
  },
  {
    src: "/imgs/icons/champions/tft8_belveth_square.tft_set8.png",
    name: "Bel'Veth",
    origin: ["Threat"],
    class: [""],
    cost: 4,
  },
  {
    src: "/imgs/icons/champions/tft8_blitzcrank_square.tft_set8.png",
    name: "Blitzrank",
    origin: ["A.D.M.I.N."],
    class: ["Brawler"],
    cost: 1,
  },
  {
    src: "/imgs/icons/champions/tft8_camille_square.tft_set8.png",
    name: "Camille",
    origin: ["A.D.M.I.N."],
    class: ["Renegade"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_chogath_square.tft_set8.png",
    name: "Cho'Gath",
    origin: ["Threat"],
    class: [""],
    cost: 3,
  },
  {
    src: "/imgs/icons/champions/tft8_draven_square.tft_set8.png",
    name: "Draven",
    origin: ["Mecha: PRIME"],
    class: ["Ace"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_ekko_square.tft_set8.png",
    name: "Ekko",
    origin: ["Star Guardian"],
    class: ["Aegis", "Prankster"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_ezreal_square.tft_set8.png",
    name: "Ezreal",
    origin: ["Underground"],
    class: ["Recon"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_fiddlesticks_square.tft_set8.png",
    name: "Fiddlesticks",
    origin: ["Threat", "Corrupted"],
    class: [""],
    cost: 5,
  },
  {
    src: "/imgs/icons/champions/tft8_fiora_square.tft_set8.png",
    name: "Fiora",
    origin: ["Ox Force"],
    class: ["Duelist"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_galio_square.tft_set8.png",
    name: "Galio",
    origin: ["Civilian"],
    class: ["Mascot"],
    cost: 1,
  },
  {
    src: "/imgs/icons/champions/tft8_gangplank_square.tft_set8.png",
    name: "Gangplank",
    origin: ["Supers"],
    class: ["Duelist"],
    cost: 1,
  },
  {
    src: "/imgs/icons/champions/tft8_janna_square.tft_set8.png",
    name: "Janna",
    origin: ["Civilian"],
    class: ["Forecaster", "Spellslinger"],
    cost: 5,
  },
  {
    src: "/imgs/icons/champions/tft8_jax_square.tft_set8.png",
    name: "Jax",
    origin: ["Mecha: PRIME"],
    class: ["Brawler"],
    cost: 5,
  },
  {
    src: "/imgs/icons/champions/tft8_jinx_square.tft_set8.png",
    name: "Jinx",
    origin: ["Anima Squad"],
    class: ["Prankster"],
    cost: 2,
  },
  {
    src: "imgs/icons/champions/tft8_kaisa_square.tft_set8.png",
    name: "Kai'sa",
    origin: ["Star Guardian"],
    class: ["Recon"],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_kayle_square.tft_set8.png",
    name: "Kayle",
    origin: ["Underground"],
    class: ["Kayle"],
    cost: 3,
  },
  {
    src: "/imgs/icons/champions/tft8_leblanc_square.tft_set8.png",
    name: "LeBlanc",
    origin: ["A.D.M.I.N."],
    class: ["Spellslinger", "Hacker"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_leesin_square.tft_set8.png",
    name: "Lee Sin",
    origin: ["Supers"],
    class: ["Brawler", "Heart"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_leona_square.tft_set8.png",
    name: "Leona",
    origin: ["Mecha: PRIME"],
    class: ["Aegis", "Renegade"],
    cost: 5,
  },
  {
    src: "/imgs/icons/champions/tft8_lulu_square.tft_set8.png",
    name: "Lulu",
    origin: ["Gadgeteen"],
    class: ["Heart"],
    cost: 1,
  },
  {
    src: "/imgs/icons/champions/tft8_lux_square.tft_set8.png",
    name: "Lux",
    origin: ["Star Guardian"],
    class: ["Spellslinger"],
    cost: 1,
  },
  {
    src: "/imgs/icons/champions/tft8_malphite_square.tft_set8.png",
    name: "Malphite",
    origin: ["Supers"],
    class: ["Mascot"],
    cost: 2,
  },
  {
    src: "/imgs/icons/champions/tft8_missfortune_square.tft_set8.png",
    name: "Miss Fortune",
    origin: ["Anima Squad"],
    class: ["Ace"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_mordekaiser_square.tft_set8.png",
    name: "Mordekaiser",
    origin: ["Laser Corps"],
    class: ["Ace"],
    cost: 5,
  },
  {
    src: "imgs/icons/champions/tft8_nasus_square.tft_set8.png",
    name: "Nasus",
    origin: ["Anima Squad"],
    class: ["Mascot"],
    cost: 1,
  },
  {
    src: "imgs/icons/champions/tft8_nilah_square.tft_set8.png",
    name: "Nilah",
    origin: ["Star Guardian"],
    class: ["Duelist"],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_nunu_square.tft_set8.png",
    name: "Nunu",
    origin: ["Gadgeteen"],
    class: ["Mascot"],
    cost: 5,
  },
  {
    src: "imgs/icons/champions/tft8_poppy_square.tft_set8.png",
    name: "Poppy",
    origin: ["Gadgeteen"],
    class: ["Defender"],
    cost: 1,
  },
  {
    src: "imgs/icons/champions/tft8_rammus_square.tft_set8.png",
    name: "Rammus",
    origin: ["Threat"],
    class: [""],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_rell_square.tft_set8.png",
    name: "Rell",
    origin: ["Star Guardian"],
    class: ["Defender"],
    cost: 2,
  },
  {
    src: "imgs/icons/champions/tft8_renekton_square.tft_set8.png",
    name: "Renekton",
    origin: ["Laser Corps"],
    class: ["Brawler"],
    cost: 1,
  },
  {
    src: "imgs/icons/champions/tft8_riven_square.tft_set8.png",
    name: "Riven",
    origin: ["Anima Squad"],
    class: ["Brawler", "Defender"],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_samira_square.tft_set8.png",
    name: "Samira",
    origin: ["Underground"],
    class: ["Sureshot", "Ace"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_sejuani_square.tft_set8.png",
    name: "Sejuani",
    origin: ["Laser Corps"],
    class: ["Brawler"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_senna_square.tft_set8.png",
    name: "Senna",
    origin: ["Laser Corps"],
    class: ["Sureshot"],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_sett_square.tft_set8.png",
    name: "Sett",
    origin: ["Mecha: PRIME"],
    class: ["Defender"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_sivir_square.tft_set8.png",
    name: "Sivir",
    origin: ["Civilian"],
    class: ["Sureshot"],
    cost: 2,
  },
  {
    src: "imgs/icons/champions/tft8_sona_square.tft_set8.png",
    name: "Sona",
    origin: ["Underground"],
    class: ["Spellslinger", "Heart"],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_soraka_square.tft_set8.png",
    name: "Soraka",
    origin: ["A.D.M.I.N."],
    class: ["Heart"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_sylas_square.tft_set8.png",
    name: "Sylas",
    origin: ["Anima Squad"],
    class: ["Renegade"],
    cost: 1,
  },
  {
    src: "imgs/icons/champions/tft8_syndra_square.tft_set8.png",
    name: "Syndra",
    origin: ["Star Guardian"],
    class: ["Heart"],
    cost: 5,
  },
  {
    src: "imgs/icons/champions/tft8_taliyah_square.tft_set8.png",
    name: "Taliyah",
    origin: ["Star Guardian"],
    class: ["Spellslinger"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_talon_square.tft_set8.png",
    name: "Talon",
    origin: ["Ox Force"],
    class: ["Renegade"],
    cost: 1,
  },
  {
    src: "imgs/icons/champions/tft8_urgot_square.tft_set8.png",
    name: "Urgot",
    origin: ["Threat"],
    class: [""],
    cost: 5,
  },
  {
    src: "imgs/icons/champions/tft8_vayne_square.tft_set8.png",
    name: "Vayne",
    origin: ["Anima Squad"],
    class: ["Duelist", "Recon"],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_velkoz_square.tft_set8.png",
    name: "Vel'koz",
    origin: ["Threat"],
    class: [],
    cost: 3,
  },
  {
    src: "imgs/icons/champions/tft8_vi_square.tft_set8.png",
    name: "Vi",
    origin: ["Underground"],
    class: ["Aegis", "Brawler"],
    cost: 2,
  },
  {
    src: "imgs/icons/champions/tft8_viego_square.tft_set8.png",
    name: "Viego",
    origin: ["Ox Force"],
    class: ["Renegade"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_wukong_square.tft_set8.png",
    name: "Wukong",
    origin: ["Mecha: PRIME"],
    class: ["Defender"],
    cost: 1,
  },
  {
    src: "imgs/icons/champions/tft8_yasuo_square.tft_set8.png",
    name: "Yasuo",
    origin: ["Laser Corps"],
    class: ["Duelist"],
    cost: 2,
  },
  {
    src: "imgs/icons/champions/tft8_yuumi_square.tft_set8.png",
    name: "Yuumi",
    origin: ["Star Guardian"],
    class: ["Mascot", "Heart"],
    cost: 2,
  },
  {
    src: "imgs/icons/champions/tft8_zac_square.tft_set8.png",
    name: "Zac",
    origin: ["Threat"],
    class: [],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_zed_square.tft_set8.png",
    name: "Zed",
    origin: ["Laser Corps"],
    class: ["Duelist", "Hacker"],
    cost: 4,
  },
  {
    src: "imgs/icons/champions/tft8_zoe_square.tft_set8.png",
    name: "Zoe",
    origin: ["Gadgeteen"],
    class: ["Hacker"],
    cost: 3,
  },
];
